### ISSUE TITLE
join button has no effect

### ISSUE THREAD

**Issue by wainaxman** [zerotier/ZeroTierNAS#1]
after installing zerotier-one.spk 1.2.2  downloaded from website,  upon clicking the 'join' button i had no effect. the browser console would show some 502s. 

- rebooted my syno and tried again, no effect
- without networkid the ui complains pressing 'join', if enter networkid and click 'join' i get no effect

DS212j
MARVELL Kirkwood 88F6281
DSM 6.1-15047 Update 1

**Comment by joseph-henry** [comment]
Hello wainaxman, 

You're probably right on the cpu incompatibility. We've built a `zerotier-one` binary for `armv5te` but we don't have this particular machine to test on. If you'd like we can send you this binary to test.

Otherwise you can try to build on another ARM machine and use the `-march=armv5te` flag and then replace the `/usr/sbin/zerotier-one` binary with your new one.

**Comment by wainaxman** [comment]
Hello joseph
I repeated the .spk installation via webinterface while looking into the /var/log/messages but it didnt yield more clues:

2017-03-30T09:48:14+02:00 hobbit synoscgi_SYNO.Core.Package.Installation_1_upload[18847]: pkgtool.cpp:1516 /volume1/@tmp/58DCB83E0/WIZARD_UIFILES/install_uifile: * Line 1, Column 1
  Syntax error: value, object or array expected.
2017-03-30T09:48:23+02:00 hobbit synoscgi_SYNO.Core.Package.Installation_1_install[18926]: resource_api.cpp:163 Acquire service-cfg for zerotier when 0x0001 (done)
2017-03-30T09:50:24+02:00 hobbit synoscgi_SYNO.Core.Package.Uninstallation_1_uninstall[20739]: resource_api.cpp:231 Release service-cfg for zerotier when 0x0004 (done)

Are there other logs you would be interested in? 

Also, since uninstalling the zerotier package the diskstation doesnt hibernate anymore. No clue if this is related to ZT or because i recently updated synology packages. I would be happy if you could send me the binary so i can report back the result.

**Comment by joseph-henry** [comment]
Interesting.

I've uploaded just the binary [here](http://office.zerotier.com/zerotier-one.armv5te), you'll need to rename it to `zerotier-one`, copy that to `/usr/sbin` on your device and try something like `zerotier-one -U -p9993 /var/log/zerotier-one &`
 
Per the log, I'd recommend taking a look at the contents of `/volume1/@tmp/58DCB83E0/WIZARD_UIFILES/install_uifile` and seeing if you can find out why it thinks there's a syntax error on that line. That file isn't one of our files, it's a native DSM file.

I don't think our package would prevent your device from hibernating since we don't mess with any power-state related stuff. But we'd be happy to continue diagnosing the problem.

**Comment by joseph-henry** [comment]
Just out of curiosity, could you check the contents of `/var/lib/zerotier-one` and see if `/usr/sbin/zerotier-one` exists before you try the above.

**Comment by wainaxman** [comment]
the asked binary exists, but cannot be executed:
```
admin@hobbit:/$ ls /var/lib/zerotier-one/ -lsatr
total 12
0 lrwxrwxrwx  1 root root   30 Mar 30 17:38 zerotier-one -> ../../../usr/sbin/zerotier-one
0 lrwxrwxrwx  1 root root   30 Mar 30 17:38 zerotier-idtool -> ../../../usr/sbin/zerotier-one
0 lrwxrwxrwx  1 root root   30 Mar 30 17:38 zerotier-cli -> ../../../usr/sbin/zerotier-one
4 -rwxr-xr-x  1 root root 3321 Mar 30 17:38 ztui_watchdog.sh
4 drwxr-xr-x  2 root root 4096 Mar 30 17:38 .
4 drwxr-xr-x 13 root root 4096 Mar 30 19:37 ..
admin@hobbit:/$ ls -lsatr /usr/sbin/zerotier-one 
1284 -rwxr-xr-x 1 root root 1312340 Mar 30 17:38 /usr/sbin/zerotier-one
admin@hobbit:/$ ./usr/sbin/zerotier-one 
-sh: ./usr/sbin/zerotier-one: No such file or directory
```

next, i swapped the binary with the one you provided and i still have the same behaviour:
```
admin@hobbit:/usr/sbin$ ls -lsatr zerotier-one
1276 -rwxr-xr-x 1 admin users 1304132 Mar 30 20:45 zerotier-one
admin@hobbit:/usr/sbin$ sudo zerotier-one -U -p9993 /var/lib/zerotier-one &
[1] 23205
admin@hobbit:/usr/sbin$ sudo: unable to execute /sbin/zerotier-one: No such file or directory
^C
[1]+  Done                    sudo zerotier-one -U -p9993 /var/lib/zerotier-one
admin@hobbit:/usr/sbin$ sudo ldd zerotier-one
sudo: ldd: command not found
admin@hobbit:/usr/sbin$ sudo file zerotier-one
sudo: file: command not found
admin@hobbit:/usr/sbin$ 
```

I sense something like this:
http://stackoverflow.com/questions/3949161/no-such-file-or-directory-but-it-exists

This is exceeding my capacity of tonight. 

Please choose what i may try this weekend:
1. reinstall syno from scratch
2. getting to know (and install) 'ldd' or 'file' ... or whatever ... and dig deeper.

PS: Hibernation was working again after a reboot. Since i reinstalled ZT it is staying awake again. Couldnt find useful hints about this in the log.

**Comment by joseph-henry** [comment]
Good morning, 

First, I noticed you tried executing the binary that's in your path with a leading `.`, try removing it like so: `/usr/sbin/zerotier-one`


Second, 
Since the tools you tried to use weren't present on your system I ran them on the machine I built the binary on for you. Try to make sure you have the libraries required.

`ldd zerotier-one` yields:

```
linux-vdso.so.1 (0x7efc6000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76d8e000)
	libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76cac000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76c31000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76c04000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76bdc000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76a9b000)
	/lib/ld-linux-armhf.so.3 (0x54b27000)
```


`file zerotier-one` yields:

```
zerotier-one: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=b644f8dd84e5c3d66b59de858cab91fe4522c14e, stripped
```

It's hard to find good information on your device but I assume it's 32-bit? If not we can build a 64-bit binary for you and re-try.

**Comment by joseph-henry** [comment]
Btw. In case you ever need it, Entware-ng will make your life much easier on NAS, there's 1700+ packages/tools that you can install via `ipkg install tool_name`.

The instructions on the first post of [this page](https://forum.synology.com/enu/viewtopic.php?f=40&t=95346&hilit=entware+ng) will get you up and running. It'll help if you ever find yourself needing to debug stuff on your NAS.

**Comment by naasking** [comment]
I've run into this issue as well on a DS413j. Zerotier works great on my x64 Synology box, but the ARM package doesn't work.

The same zerotier-one executable appears to be installed under `/sbin`, `/usr/sbin` and `/volume1/@appstore/zerotier/bin`. Executing any of them simply returns the error described above:

    root:host:/# /sbin/zerotier-one
    -ash: /sbin/zerotier-one: No such file or directory

Since you asked about the CPU, here's the output of cat /proc/cpuinfo if that helps:

    Processor       : Feroceon 88FR131 rev 1 (v5l)
    BogoMIPS        : 1589.24
    Features        : swp half thumb fastmult edsp
    CPU implementer : 0x56
    CPU architecture: 5TE
    CPU variant     : 0x2
    CPU part        : 0x131
    CPU revision    : 1
    
    Hardware        : Synology 6282 board
    Revision        : 0000
    Serial          : 0000000000000000

Let me know if there's some way to assist as I'd really like to get this working.

**Comment by naasking** [comment]
Forgot to mention, this is on DSM 6.1-15047. `/lib/ld-linux-armhf.so.3` is definitely missing, and if I create a symbolic link `ln -s /lib/ld-linux.so.3 /lib/ld-linux-armhf.so.3`, executing zerotier-one now prints out:

    /sbin/zerotier-one: /lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /sbin/zerotier-one)
    /sbin/zerotier-one: /lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /sbin/zerotier-one)

So it seems the C++ ABI version in DSM 6 isn't compatible with the one used to build the ARM package.

**Comment by joseph-henry** [comment]
Thank you for the information. We've now ordered a DS216j to test on, and will begin testing next Monday, we should have a working version for ARMv5TE-based processors (which the DS413j also uses) soon. Thanks for your patience and help guys! I'll keep you both up to date on our progress.

**Comment by false** [comment]
I have the same problem on a DS214play using 1.2.4 build ; Join button won't do anything.

**Comment by wainaxman** [comment]
I just installed 1.2.4 and it joined the network ... awesome job guys!

DS212j
MARVELL Kirkwood 88F6281
DSM 6.1.3-15152 Update 3
