### ISSUE TITLE
QNAP QTS 5.0.0 and newer doesn't support

### ISSUE THREAD

**Issue by Delliaf** [zerotier/ZeroTierNAS#124]
After updating to v5 it doesn't work:

[App Center] Failed to install ZeroTier. Downgrade QTS to 5.0.0 or an older compatible version.

[App Center] Failed to start ZeroTier. QTS does not support this ZeroTier version. Check for updates in "App Center" or on the official app website.

[zerotier_1.8.4]

**Comment by Androad** [comment]
It works well in V5.0.0 in recent days,but fail to start from today that QNAP release V5.0.1 version.

**Comment by Delliaf** [comment]
> It works well in V5.0.0 in recent days,but fail to start from today that QNAP release V5.0.1 version.

For now, you can use Docker:
https://discuss.zerotier.com/t/zerotier-not-compatible-with-qts-5-0-1/7701/4

**Comment by octimot** [comment]
@Delliaf until this is fixed, would you mind detailing how you got the docker container to work?

On our end, we managed to start it up and connect to the zerotier network, but for some reasons other network members cannot access the NAS, nor the NAS cannot see other members.

**Comment by Delliaf** [comment]
> @Delliaf until this is fixed, would you mind detailing how you got the docker container to work?
> 
> On our end, we managed to start it up and connect to the zerotier network, but for some reasons other network members cannot access the NAS, nor the NAS can see other members.

I had no problems, did everything as written in the link that I attached.  I installed QVPN in the store, logged in via SSH and executed 2 commands, changing the network ID to my own and it all worked.

Perhaps you entered the wrong network ID or did not confirm the device in the control panel?

**Comment by octimot** [comment]
@Delliaf Thanks for your reply! Yep, the device appears in the zerotier control panel and even has the status of online, but there's no way to reach it from other machines in the zerotier network. Also, on restart it joins with a different member id. Did you sudo the commands or simply ran them as non-root?

**Comment by Delliaf** [comment]
> Did you sudo the commands or simply ran them as non-root?

@octimot run as non-root

**Comment by octimot** [comment]
@Delliaf That's weird! Thanks for the info! We'll give it another shot from scratch and see if it works.

**Comment by spannerman79** [comment]
@octimot I suggest that you use docker-compose.

_Unlike_ that link that was poisted above you don't need QVPN (I never had it and never did)

I cannot reply to the discussion in that link as it is older then 30 days and locked.

**Comment by octimot** [comment]
After trying the zyclonite/zerotier docker image on 2 QNAP machines, I managed to make it work using the docker commands above! For some reason though, our TS-431X2 doesn't want to create the identity files (maybe this is a docker file permission issue or something), so zerotier will asign a new member ID each time the image or NAS is restarted.

@spannerman79 How would your configuration and docker-compose look like?

For those interested until the bug is fixed, some people have found some workarounds here: https://discuss.zerotier.com/t/qnap-failed-to-install-zerotier-downgrade-qts-to-5-0-0-or-an-older-compatible-version/9346/7 

I personally, would still prefer to use the docker solution as soon as I learn how. :-D

**Comment by spannerman79** [comment]
I already covered this over on reddit - https://www.reddit.com/r/qnap/comments/xgxydw/zerotier_with_qts_501/iouysbz/?context=3

I don't use QNAP's UI other then to just create users and shares.  As to docker I either SSH in or use portainer due to the utter shitty interface that QNAP provides in the so called "Container Station" UI.

**Comment by octimot** [comment]
@spannerman79 I agree, the Container Station UI is completely useless for any advanced options. The only reason we're using the QNAP Control Panel is that we're unsure if stuff would break on updates/restarts if we don't use it...

Thanks for the info, I'll look into it!!

**Comment by spannerman79** [comment]
> our TS-431X2 doesn't want to create the identity files

Thats a 32-bit ARM CPU.  I've yet to see a docker image that supports that.

Hardware limitation.

**Comment by octimot** [comment]
The container with the zyclonite/zerotier image starts up fine and it connects to the zerotier network. The only problem is that it doesn't save the identity files...

**Comment by spannerman79** [comment]
You **need** to define a volume mount to save the data.  If you don't then no conf files created so no joining network.

**Comment by joseph-henry** [comment]
Just FYI. This issue was resolved in [1.10.1](http://download.zerotier.com/dist/qnap/) but this thread wasn't updated at the time, my apologies. I'm transferring this issue to the [zerotier/zerotierone](https://github.com/zerotier/ZeroTierOne) repo and closing it. If anyone has any additional issues please open a ticket there and I'd be happy to take a look. Thank you.
