### ISSUE TITLE
Synology NAS unreachable after turning on vSwitch (until reboot)

### ISSUE THREAD

**Issue by schmiqt** [zerotier/ZeroTierNAS#31]
I have a DS918+ running "DSM 6.2-23739 Update 2" with ZeroTier v1.2.8r0. One ethernet port connected.

Everything is running smoothly in general. However, when I turned on vSwitch (Control Panel->Network->Network Interface->Manage->Open vSwitch Settings->Enable Open vSwitch) I was no longer able to connect to the NAS remotely.

After turning on vSwitch and before I was able to get local, ZeroTier Central showed the NAS reporting online for days while it wasn't actually reachable through a ZeroTier connection.

Once I was local again, I logged into the NAS and saw that the ZeroTier network interface was missing from Control Panel->Network->Network Interface.

Given the above two points, it seems like part of the ZeroTier service was communicating out to ZeroTier Central, but DSM removed the network interface or something when turning on vSwitch - so it wasn't effectively online.

I rebooted the NAS and I was then able to connect to the it through ZeroTier.

Expected result:
Can still connect to NAS via ZeroTier.
If NAS isn't actually reachable via ZeroTier, ZeroTier Central wouldn't show its status as Online. But it's also not exactly offline.

**Comment by joseph-henry** [comment]
Are you still experiencing this issue @schmiqt? I haven't seen this happen before, but I could provide you with a new package to try.

**Comment by SuperRoach** [comment]
FWIW, I too have an inaccessible NAS (DS415+) after enabling this option

**Comment by Spass1966** [comment]
Confirmed on my DS-218+

**Comment by joseph-henry** [comment]
Hey everyone, my apologies for taking so long on this. Here's an [updated set of packages](https://download.zerotier.com/PRERELEASES/1.4.0pre/synology) to preview `1.4.0`. It addresses the following issues:

 - Losing interface on reboot: `insmod /lib/modules/tun.ko` issued upon each reboot (and start of the service). See tickets #41 and #43 
 - Identity files moved to more traditional location `/var/lib/zerotier-one`, and are now preserved across uninstalls, reinstalls, updates, etc. Prior to this version, during uninstall we were intentionally deleting your identity files just for thoroughness but this seems to be annoying to most users (rightly so). So uninstalling and updating to this version is the last time that your configuration will get wiped. See tickets #41
 - Service script now sends proper SIGKILL signal
 - Segfault on ARM (*might* be fixed), see ticket #52
 - Memory leak (*might* be fixed), see ticket #46

To view logs for this package, see: `/var/log/packages/zerotier.log`

For this particular issue, since I've made a modification to the start/stop script it might help if you toggled the service status after enabling vSwitch. Let me know if that works.

**Comment by jaques-sam** [comment]
Hu, I have exactly the same issue today with my DS417+ (latest DSM 7). It happened when the VMM app requested to enable it. I could still use the other ethernet port until I tried to enable balanced-SLB (as IP of the first ethernet port was used I guess?).
EDIT: I not using ZeroTier any more because of DSM 7, sorry for the confusion. If somebody can direct me to the right place...? Could be an internal Synology problem :(
