### ISSUE TITLE
ZeroTier breaks after DSM update (Partially-Solved)

### ISSUE THREAD

**Issue by anadin** [zerotier/ZeroTierNAS#4]
I have been running this perfectly on DS1817+'s for a month or so but today updated the DSM and it is no longer connecting/joining.

I removed the package and reinstalled and now on that NAS, it will not even launch.

**Comment by joseph-henry** [comment]
For some reason upgrading DSM sometimes breaks ZeroTier. We've tried replicating this in-house and don't see it with our devices yet. Re-installing ZeroTier after the update always seems to do the trick. 

I've edited the title of your issue so that it's more descriptive for people searching for this problem. Thanks for opening the ticket.

**Comment by joseph-henry** [comment]
For some reason upgrading DSM sometimes breaks ZeroTier. We've tried replicating this in-house and don't see it with our devices yet. Re-installing ZeroTier after the update always seems to do the trick. 

I've edited the title of your issue so that it's more descriptive for people searching for this problem. Thanks for opening the ticket.

**Comment by anadin** [comment]
Yup that seems to have solved it thanks - its a bit of a pain though as when joining again its a different host but at least it works
