### ISSUE TITLE
Synology RS819 - Realtek RTD1296 SoC

### ISSUE THREAD

**Issue by alatteri** [zerotier/ZeroTierNAS#97]
Need build for this Synology model.

**Comment by joseph-henry** [comment]
A bit late but here are the latest [1.8.6 packages for DSM 6.2.4](http://download.zerotier.com/RELEASES/1.8.6/dist/synology/). Which includes a build for RTD1296. Since I don't have a box with that chip architecture I haven't personally tested the RTD1296 package. Let me know if you have any issues.

We'll continue to periodically make releases for DSM 6 until Synology officially EOLs it in 2023. We have a [docker solution for DSM 7](https://docs.zerotier.com/devices/synology) but I'm not certain docker is well supported for your arch.
